### ISSUE TITLE
Why specifying indirect dependencies?

### ISSUE THREAD

**Issue by Mike-Devel** [raffienficiaud/boost-cmake#1]
I've seen that you often specifiy transitive dependencies. E.g. here:
https://github.com/raffienficiaud/boost-cmake/blob/5d1124b5d96ace853aa769d2b178b81fc00144f5/boost/libs/test/build/CMakeLists.txt#L87
https://github.com/raffienficiaud/boost-cmake/blob/5d1124b5d96ace853aa769d2b178b81fc00144f5/boost/libs/filesystem/build/CMakeLists.txt#L45

I'm not sure if there is a technical reason for it (didn't really analyze the library yet) but that seems to be a red herring that something is amiss:

 If you `target_link_libaries(foo PUBLIC bar)`  and target_link_libraries(bar PUBLIC baz)` cmake automatically adds `baz` to the dependencies of  `foo`, so doing this manually is either redundant or there is something wrong with the way the dependencies of `bar` are specified.

**Comment by raffienficiaud** [comment]
You are right, this was just laziness while I was developing the boost.test/system/filesystem parts. But as soon as you create the corresponding `boost-decl.cmake` and `CMakeLists.txt`, the dependencies and interfaces are propagated properly. 

Even for header only libs, you have to declare their dependencies in the `PUBLIC` interface, and those targets should already exist somewhere in the super-project. For `boost::iterator` for instance, I would declare an explicit dependency to `boost::mpl`.

The current design does not currently require a `boost-decl.cmake` nor a `CMakeLists.txt`. This is not ideal, it does not scale very well in the number of packages. But the benefit is that it helps the transition to cmake. This is also a decision that needs to be accepted. If none of those files are present (`boost-decl.cmake` / `CMakeLists.txt`), we suppose that the library is header-only and we cannot infer the PUBLIC interface.

Let me know if this clarifies your comments.

**Comment by Mike-Devel** [comment]
> Let me know if this clarifies your comments.

yes it did. Thank you
